### ISSUE TITLE
Text in Code should be in JSON Format

### ISSUE THREAD

**Issue by brian-chalfant** [brian-chalfant/OregonTrail#1]

**Comment by kchevali** [comment]
I had to include a library to parse the json files so let me know if you are having any issues with running the project in my branch and we might need to talk on how to build the project since I’m not using IntelliJ. If everything seems good then I will create the pull request and merge my changes in.

**Comment by kchevali** [comment]
Closed by 82fd5295bff7d4e176b445dd7956f71809168ded
